apiVersion: batch/v1
kind: CronJob
metadata:
  name: microservice-test-cron
  namespace: base-platform
spec:
  schedule: "0 */5 * * *"  # every 5th hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-runner
            image: lahiru1029/test-suite-develop:latest
            command: ["python"]
            args: ["test_services.py"]
            imagePullPolicy: Always
          restartPolicy: Never
      backoffLimit: 3